//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerAssemblyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string processor { get; set; }
        public string videoCard { get; set; }
        public string disc { get; set; }
        public string korpus { get; set; }
        public string mouse { get; set; }
        public string ozu { get; set; }
        public string keyboard { get; set; }
        public string kuler { get; set; }
        public string date { get; set; }
        public string FIO { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public int price { get; set; }
    }
}
